name: "PlayerVaults"
author: UniSteven
version: "4.0"
api-version: 1.16
description: "Playervaults"
main: me.unisteven.PlayerVault
softdepend: [PlaceholderAPI]
commands:
  playervault:
    description: "Playervaults command"
    aliases: [pv]
permissions:
  playervaults.limit.*:
    description: Allows you to open a certain amount of playervaults.
    default: false
  playervaults.admin.*:
    description: Allows you to execute all playervault admin command
    default: false
  playervaults.admin.open:
    description: Allows you to open some-one their playervault
    default: false
  playervaults.admin.alter:
    description: Allows you to alter the playervault of some-one else
    default: false
  playervaults.admin.reload:
    description: Allows you to reload the config
    default: false